### ISSUE TITLE
Unknown status of CI

### ISSUE THREAD

**Issue by BNAndras** [exercism/lfe#180]
@ErikSchierboom, https://github.com/exercism/lfe/blob/main/appveyor.yml was last touched 7 years ago. Shouldn't this be moved to a GH action like maybe what [Elixir](https://github.com/exercism/elixir/blob/main/.github/workflows/ci.yml) and [Erlang](https://github.com/exercism/erlang/blob/main/.github/workflows/main.yml) have? I can play with it in December or January if another volunteer more knowledgeable doesn't want to take this on.

**Comment by ErikSchierboom** [comment]
Yes! I even see a `.travis.yml` file. Both the appveyor and travis integrations should be replaced in favor of GitHub Actions.

**Comment by BNAndras** [comment]
Moving forward with this next week. I think my approach would be to use the test runner image to test each exercise. That'll simplify things a lot so I don't get lost in the weeds with figuring out rebar3.
