### ISSUE TITLE
CI fails on testing `binary`

### ISSUE THREAD

**Issue by BNAndras** [exercism/lfe#205]
```
Tests for binary have failed:
{
  "version": 1,
  "status": "fail",
  "message": "make: *** [Makefile:20: test] Error 1"
}
```

**Comment by BNAndras** [comment]
@ErikSchierboom, the example solution passes locally with the test runner image, and the CI uses that image as well. I think the problem is that although `binary` is the slug name, the exercise uses `binary-string` in a few places. So if we rename those to binary, the CI should pass hopefully.

The only thing I don't get is that this should have come up when I first added the test CI. As recently as two weeks, the CI was working just fine in https://github.com/exercism/lfe/actions/runs/8248260729/job/22558192657.

**Comment by ErikSchierboom** [comment]
> The only thing I don't get is that this should have come up when I first added the test CI.

That is very odd. I don't see anything wrong with the CI script 🤔

**Comment by BNAndras** [comment]
The CI seems to pass without anything being changed to `binary` so this may just  be an intermittent issue to look out for.
