### ISSUE TITLE
Update ABOUT.md

### ISSUE THREAD

**Issue by BNAndras** [exercism/lfe#213]
https://github.com/exercism/lfe/blob/main/docs/ABOUT.md could be punched up a little. This documentation appears when students open the track before enrolling, so this should be more of a quick sales pitch about what makes LFE special / worth engaging.

**Comment by Santiago00lp** [comment]
Hi, I'm new to Exercim and I want to help with this issue. I have a new version of the document. Where should I commit the doc?

**Comment by BNAndras** [comment]
https://github.com/exercism/lfe/blob/main/docs/ABOUT.md is the file in question.

**Comment by kotp** [comment]
#248 may close this issue once it is merged.
