### ISSUE TITLE
Clean up exercise files

### ISSUE THREAD

**Issue by BNAndras** [exercism/lfe#256]
@kotp, I'd like to propose some cleanup.

For starters, I'd like to go through the remaining exercises and fill out the empty file stubs.

```lisp
(defmodule exercise-slug
  (export (function-being-tested 1)))

  ; Please implement the function-being-tested function.
```

Second, I want to drop the .gitignore files in each exercise since they're largely clutter. We already have a global .gitignore file.

Third, I want to fill out the description for every exercise's `src/exercise-slug.app.src` file since `make test` wants this filled out on some LFE versions. https://github.com/exercism/erlang/blob/881e88d00dc42176b046b743f566a40625fbd887/exercises/practice/clock/src/clock.app.src#L2 is an example of how that's filled out on the Erlang track, and we can do something similar like "exercism.org - clock".

Fourth, the rebar config files are marked as invalidators, but I think the rebar lock and app.src files  should be as well.

Fifth, the indent size is set to 4 spaces, but I think this should be set to 2 spaces judging from the LFE code.

Anything else I missed or something I shouldn't do from this initial list?

**Comment by kotp** [comment]
- [ ] Populate file stubs
- [ ] Remove individual `.gitignore` files for exercises
- [ ] Populate `src/exercise-slug.app.src`
- [ ] Expand `  "invalidator": [  "rebar.config" ]` entry to include `rebar.lock` and `app.src` files
- [ ] Indentation to two spaces.

The [Lisp Style Tips for the Beginner] is a pretty clear no-nonsense (and less "by consensus, check your editor") reference, I think.
 
[Lisp Style Tips for the Beginner]: https://ccrma.stanford.edu/CCRMA/Courses/AlgoComp/cm/doc/contrib/lispstyle.html
