### ISSUE TITLE
Getting started needs update.

### ISSUE THREAD

**Issue by NobbZ** [exercism/lfe#26]
Currently the getting started seems to mention a lot of rebar2 stuff, but the makefile uses rebar3 and does make many of the steps mentioned obselete.

**Comment by yurrriq** [comment]
Ah, good catch. Thanks!

**Comment by yurrriq** [comment]
#### Update
- [ ] SETUP.md (bad link: exercism help page)
- [ ] docs/INSTALLATION.md (mention rebar3)
- [ ] docs/TESTS.md (s/rebar2/rebar3/g)

**Comment by yurrriq** [comment]
@NoobZ, where is this getting started you mention? I can't seem to find it.

**Comment by NobbZ** [comment]
What I meant was the whole set of pages you get when you click Languages ->
LFE in exercisms menu: http://exercism.io/languages/lfe, especially
“running the tests” section was/is very misleading.

Eric Bailey <notifications@github.com> schrieb am Sa., 19. März 2016 um
19:06 Uhr:

**Comment by yurrriq** [comment]
Cool. I wasn't sure if there was another page somewhere. The checklist I posted should suffice.

**Comment by yurrriq** [comment]
Related: http://blog.lfe.io/tutorials/2016/03/25/0858-lfe-and-rebar3/
