### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by iHiD** [exercism/lfe#271]
@kahgoh, @yurriq You both qualify to be maintainers here. Thank you for your hard work! Would you like to join?

**Comment by BNAndras** [comment]
@yurrriq I believe

**Comment by kahgoh** [comment]
Thanks for the offer. It's a yes from me 😀

**Comment by ErikSchierboom** [comment]
@kahgoh Awesome. Thank you!

You've been added to the team. You have access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)

**Comment by yurrriq** [comment]
I'm pretty sure I created this track in the first place, heh. Unfortunately, I've not been using LFE for a few years now, but I'm happy to be a backup reviewer or help out occasionally. Thanks, @kahgoh!

**Comment by ErikSchierboom** [comment]
@yurrriq Awesome. Thank you!

You've been added to the team. You have access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
