### ISSUE TITLE
Gitter chat, common BEAM channel

### ISSUE THREAD

**Issue by NobbZ** [exercism/lfe#51]
In Exercism there are a couple of gitter-channels used to coordinate development on exercism, the product.

Also there is a global support channel and throughout exercism there are a couple of tracks that have a support channel on gitter.im. Erlang has one as well, but it isn't used quite much.

Since Erlang, Elixir, and LFE do share the same base technology (BEAM-VM) and in case of LFE even the same standard library, I'd suggest to join forces in a single gitter-channel (former erlang channel).

I can't rename the room, but already changed its headline to "Exercism Exercises in BEAM Powered Languages (Erlang, Elixir, LFE)"

If you do not want to join the channel please feel free to deny, I will remove your language from the headline. Also once joined, you are able to split into your own channel once the traffic explodes ;)

**Comment by yurrriq** [comment]
:+1:

**Comment by kotp** [comment]
For reference [Erlang, Elixir, LFE](https://gitter.im/exercism/xerlang) gitter room.
