### ISSUE TITLE
Fix the Hello World exercise so it passes with 'make test' on CI

### ISSUE THREAD

**Issue by kytrinyx** [exercism/lfe#82]
I do not know if this is failing locally, but on Travis CI we are getting the following failure:

```
===> Compiling exercises/hello-world/src/hello-world.lfe failed
/home/travis/build/exercism/lfe/exercises/hello-world/src/hello-world.lfe:9999: unbound function: #(from 1)
make: *** [test] Error 1
The command "make test" exited with 2.
```

**Comment by NobbZ** [comment]
Glancing over it, it was introduced in #79. For some reason there has no travis run taken place for that PR. If it were it would have catched the problem.
